name: docker-publish

on:
  push:
    tags:
      - "v*.*.*"
jobs:
  docker:
    runs-on: ubuntu-latest
    environment: dockerhub
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          file: Dockerfile.nitro
          build-args: |
            RUST_TOOLCHAIN=1.66.1
          tags: |
            cryptocom/nitro-enclave-tmkms:latest
            cryptocom/nitro-enclave-tmkms:${{ steps.get_version.outputs.VERSION }}
